# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70039989ad9ad0001681718a8b6f5cb992d5d4cd996780d4c9e1fb3c9c4c2f8d7fc38f3983dfe0bbc4ebc7b8d79cf324862ef5ee3c8ad08ccf4c1e19696dfaa7

test:
  secret_key_base: 3e406d9cafacb25d05d02cd945da957ee65947582ac09c41a99377f9b49140e44a29f7862e8a042f20fc4396b20308b89e362feda0275a20e9659e14b251989a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
